version: 3.16.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2022
configuration: Release
before_build:
  - nuget restore
build:
  parallel: true
  verbosity: minimal
after_build:
  - cmd: msbuild /m /t:Pack /p:Configuration=Release /p:PackageOutputPath=../../nugets
artifacts:
  - path: "nugets/**"
    name: NuGet
deploy:
  - provider: NuGet
    server: https://www.myget.org/F/where/api/v2/package
    api_key:
      secure: ccLeQ7ilTGmrpiJV5QccGxBslwLFzKYNGedGwCz8EVjSpPXWC3KMDlzfQyhm+9mz
    symbol_server: https://www.myget.org/F/where/api/v3/index.json
    on:
      branch: myget
