<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <DefineConstants>TRACE;ALGLIB_USE_SIMD</DefineConstants>
    <NoWarn>$(NoWarn);CS1591;CS8981</NoWarn>
    <SuppressTfmSupportBuildWarnings>false</SuppressTfmSupportBuildWarnings>
	  <TargetFrameworks>net5.0;net6.0;net7.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net7.0'))">True</IsAotCompatible>
    <IsTrimmable Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net6.0'))">True</IsTrimmable>
  </PropertyGroup>

  <PropertyGroup>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>license.txt</PackageLicenseFile>
    <Product>ALGLIB for C# (unsafe with NET5 SIMD intrinsics)</Product>
    <Title>alglib.net</Title>
  </PropertyGroup>

  <ItemGroup>
    <None Include="license\license.txt" Pack="true" PackagePath="$(PackageLicenseFile)" />
    <None Include="images\icon.png" Pack="true" PackagePath="\" />
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
