<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <NoWarn>$(NoWarn);CS1591;CS8981;NU1902;NU1903</NoWarn>
    <SuppressTfmSupportBuildWarnings>false</SuppressTfmSupportBuildWarnings>
	  <TargetFrameworks>net2.0;net4.0-client;net5.0;net6.0;net7.0;netcoreapp2.1;netstandard2.0;uap10.0.15138.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net7.0'))">True</IsAotCompatible>
    <IsTrimmable Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net6.0'))">True</IsTrimmable>
  </PropertyGroup>

  <PropertyGroup>
    <PackageIcon>icon.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>license.txt</PackageLicenseFile>
    <Product>ALGLIB for C# (managed)</Product>
    <Title>alglib.net</Title>
  </PropertyGroup>

  <ItemGroup>
    <None Include="license\license.txt" Pack="true" PackagePath="$(PackageLicenseFile)"/>
    <None Include="images\icon.png" Pack="true" PackagePath="\"/>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
